
package SIIL.Administracion.Cheques;

import SIIL.Server.Database;
import SIIL.Server.MySQL;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 * Create and update
 * @author Azael
 */
public class CU extends javax.swing.JInternalFrame 
{

    /**
     * Creates new form CU
     */
    public CU(String bd,ChequeRow chrow) 
    {
        initComponents();
        BD = bd;
        grOption.add(opDolar);
        grOption.add(opPesos);
        cheque = new Cheque();
        cheque.setRow(chrow);
        fhDepo.setEnabled(false);
        txClient.setEnabled(false);
        btClient.setEnabled(false);
        txNum.setEnabled(false);
    }
    
    /**
     * Creates new form CU
     */
    public CU(String bd,Cheque ch) 
    {
        initComponents();
        BD = bd;
        grOption.add(opDolar);
        grOption.add(opPesos);
        cheque = ch;
        load();        
    }

    private void load() 
    {
        date.setDate(cheque.getFh());
        comp = cheque.getComp();
        txClient.setText(comp.getNumber());
        lbClient.setText(comp.getName());
        txMonto.setText(String.valueOf(cheque.getMonto()));
        if(cheque.getMoneda().equals("mxn"))
        {
            opPesos.setSelected(true);
        }
        else if(cheque.getMoneda().equals("dll"))
        {
            opDolar.setSelected(true);
        }
        
        txSerie.setText(cheque.getFactSerie());
        txFolio.setText(String.valueOf(cheque.getFactFolio()));
        txNum.setText(String.valueOf(cheque.getNumber()));
        txaNote.setText(cheque.getNote());
    }
    
    /**
     * Creates new form CU
     */
    public CU(String bd) 
    {
        initComponents();
        BD = bd;
        grOption.add(opDolar);
        grOption.add(opPesos);
        cheque = new Cheque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grOption = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        date = new org.jdesktop.swingx.JXDatePicker();
        btClient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txClient = new javax.swing.JTextField();
        lbClient = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txMonto = new javax.swing.JTextField();
        opPesos = new javax.swing.JRadioButton();
        opDolar = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txSerie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txFolio = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaNote = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txCambio = new javax.swing.JTextField();
        fhDepo = new org.jdesktop.swingx.JXDatePicker();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Captura Factura");

        jLabel1.setText("Fecha Factura");

        btClient.setText("...");
        btClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente");

        txClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txClientKeyReleased(evt);
            }
        });

        lbClient.setText("##");

        jLabel2.setText("Total");

        opPesos.setText("Pesos");
        opPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPesosActionPerformed(evt);
            }
        });

        opDolar.setText("Dolar");
        opDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDolarActionPerformed(evt);
            }
        });

        jLabel3.setText("Moneda");

        jLabel4.setText("Factura");

        jLabel5.setText("Serie");

        jLabel7.setText("Folio");

        btSave.setText("Guardar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero de Cheque");
        jLabel8.setToolTipText("");

        jLabel9.setText("Nota");

        txaNote.setColumns(20);
        txaNote.setRows(5);
        jScrollPane1.setViewportView(txaNote);

        jLabel10.setText("T. Cambio");

        jLabel11.setText("Fecha Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btClient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(opPesos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(opDolar))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txNum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txMonto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(fhDepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btSave)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhDepo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txClient, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClient, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opPesos)
                    .addComponent(opDolar)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSave)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientActionPerformed
        comp = new SIIL.Server.Company();
        JFrame frm = new JFrame();
        JDialog dlg = new JDialog(frm,"Seleccionar cliente",true);
        MySQL conn = new MySQL();
        conn.Create();
        if(conn.getConnection() == null)
        {
            JOptionPane.showMessageDialog(this,
                "Conexion a Servidor Invalida",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        SIIL.Clientes.ReadSelect read = new SIIL.Clientes.ReadSelect(comp,BD);
        dlg.setContentPane(read);
        dlg.setSize(460, 260);
        dlg.setVisible(true);
        txClient.setText(comp.getNumber());
        lbClient.setText(comp.getName());
    }//GEN-LAST:event_btClientActionPerformed

    private void txClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txClientKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            comp = new SIIL.Server.Company();
            comp.setBD(BD);
            comp.setNumber(txClient.getText());
            SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();        
            Database dbserver = null;
            try 
            {
                serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
                dbserver = new Database(serverConfig);
            } 
            catch (ClassNotFoundException | SQLException | IOException | ParserConfigurationException | SAXException ex) 
            {
                JOptionPane.showMessageDialog(this,
                    "Fallo importacion.",
                    "Error Interno",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        
            if(comp.complete(dbserver))
            {
                lbClient.setText(comp.getName());
            }
            else
            {
                if(comp == null)
                {
                    JOptionPane.showMessageDialog(this, "Numero de cliente desconocido",
                        "Error externo", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    comp=null;
                    lbClient.setText("###");
                }
            }
            dbserver.close();
        }
    }//GEN-LAST:event_txClientKeyReleased

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
  
        cheque.setSucursal(SIIL.servApp.cred.getSuc());
        
        if(date.getDate() != null)
        {
            cheque.setFh(date.getDate());
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique la fecha del cheque",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if(comp != null)
        {
            cheque.setComp(comp);
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique el cliente",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if(txMonto.getText().matches("^[0-9]+(.[0-9]{1,2})$"))
        {
            cheque.setMonto(Float.parseFloat(txMonto.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique el monto del cheque con dos decimales",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );    
            return;        
        }
                
        if(opDolar.isSelected())
        {
            cheque.setMoneda("dll");
            if(txCambio.getText().matches("^[0-9]{1,3}(.[0-9]{4,4})$"))
            {
                cheque.setTcambio(Float.parseFloat(txCambio.getText()));
            }
            else
            {
                JOptionPane.showMessageDialog(null,
                    "El tipo cambio es de 1 a 3 digitos para la parte entera y 4 digitos para la parte decimal",
                    "Error Externo",
                    JOptionPane.ERROR_MESSAGE
                    );    
                return;        
            }
        }
        else if(opPesos.isSelected())
        {
            cheque.setMoneda("mnx");
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique la moneda",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                ); 
            return;
        }
        
        if(txSerie.getText().length() > 0)
        {
            cheque.setFactSerie(txSerie.getText().toUpperCase());
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique la Serie de la factura",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                ); 
            return;
        }
        
        if(txFolio.getText().length() > 0)
        {
            cheque.setFactFolio(Integer.parseInt(txFolio.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique el Folio de la factura",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                ); 
            return;
        }
        
        if(txNum.getText().matches("^[0-9]{4,16}$"))
        {
            cheque.setNumber(Integer.parseInt(txNum.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "El numero de cheque es un entero de 4 digitos, sin letras, simbolos ni espacios",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if(txaNote.getText().indexOf('\'') == -1 && txaNote.getText().indexOf('\"') == -1 )
        {
            cheque.setNote(txaNote.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "No se permite el uso de comillas simples o dobles",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if(fhDepo.getDate() != null)
        {
            cheque.setFhDeposito(fhDepo.getDate());
        }
        else
        {
            JOptionPane.showMessageDialog(null,
                "Indique la fecha del deposito",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();        
        Database dbserver = null;
        try 
        {
            serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
            dbserver = new Database(serverConfig);
        } 
        catch (ClassNotFoundException | SQLException | IOException | ParserConfigurationException | SAXException ex) 
        {
            JOptionPane.showMessageDialog(this,
                "Fallo importacion.",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }       
        
        //Es actualizacion
        int res = 0;
        if(cheque.getID() != 0)
        {
            res = cheque.update(dbserver); 
        }
        else
        {
            //si se esta corriendo la nueva version
            if(chrow != null)
            {
                res = cheque.insert(dbserver,chrow);
            }
            else
            {
                res = cheque.insert(dbserver);     
            }
        }
        if(res == 1)
        {
            try 
            {
                dbserver.commit();
                JOptionPane.showMessageDialog(this,"Operación completa");
                dispose();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(CU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try 
            {
                dbserver.rollback();
                JOptionPane.showMessageDialog(this,
                "Operación cancelada",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
                );
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(CU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void opDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDolarActionPerformed
        txCambio.setEnabled(true);
    }//GEN-LAST:event_opDolarActionPerformed

    private void opPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPesosActionPerformed
        txCambio.setEnabled(false);
    }//GEN-LAST:event_opPesosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClient;
    private javax.swing.JButton btSave;
    private org.jdesktop.swingx.JXDatePicker date;
    private org.jdesktop.swingx.JXDatePicker fhDepo;
    private javax.swing.ButtonGroup grOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClient;
    private javax.swing.JRadioButton opDolar;
    private javax.swing.JRadioButton opPesos;
    private javax.swing.JTextField txCambio;
    private javax.swing.JTextField txClient;
    private javax.swing.JTextField txFolio;
    private javax.swing.JTextField txMonto;
    private javax.swing.JTextField txNum;
    private javax.swing.JTextField txSerie;
    private javax.swing.JTextArea txaNote;
    // End of variables declaration//GEN-END:variables

    SIIL.Server.Company comp;
    String BD;
    Cheque cheque;
    ChequeRow chrow;
}
