
package SIIL.purchase.privider.crud;

import SIIL.Server.Database;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Azael
 */
public class Create extends javax.swing.JInternalFrame {

    /**
     * Creates new form Create
     */
    public Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txRFC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txAccount = new javax.swing.JTextField();
        spDiasC = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("RFC");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cuenta Con.");

        spDiasC.setValue(14);

        jLabel4.setText(" Dias de Credito");

        btSave.setText("Guardar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDiasC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spDiasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        SIIL.purchase.ProviderMXSIIL prov = new SIIL.purchase.ProviderMXSIIL();
        
        if(txRFC.getText().length() > 10)
        {
            prov.setRFC(txRFC.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                "Indique un RFC valido",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if(txName.getText().length() > 0)
        {
            prov.setName(txName.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                "Indique un Nombre Valido",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if((int) spDiasC.getValue() > 0)
        {
            prov.setDayCredit((int) spDiasC.getValue());
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                "Indique los dias de credito",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }
        
        if(txAccount.getText().length() > 0)
        {
            prov.setAccount(txAccount.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                "Indique un Cuenta Valida",
                "Error Externo",
                JOptionPane.ERROR_MESSAGE
                );
            return;
        }

        SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();        
        Database dbserver = null;
        try 
        {
            serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
            dbserver = new Database(serverConfig);
        } 
        catch (ClassNotFoundException | SQLException | IOException | ParserConfigurationException | SAXException ex) 
        {
            JOptionPane.showMessageDialog(this,
                "Fallo importacion.",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        prov.createID(dbserver);
        int res = 0;
        try 
        {
            res = prov.insert(dbserver);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(res == 1)
        {
            try 
            {
                dbserver.commit();                
                JOptionPane.showMessageDialog(this,
                "Todos los cambios se realizaron exitosamente"
                );
                dispose();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try 
            {
                dbserver.rollback();
                JOptionPane.showMessageDialog(this,
                "Un error desconocido ocurrio los datos no seran guardados",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
                );
                return;
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spDiasC;
    private javax.swing.JTextField txAccount;
    private javax.swing.JTextField txName;
    private javax.swing.JTextField txRFC;
    // End of variables declaration//GEN-END:variables
}
