
package SIIL.Servicios.Grua;

import SIIL.Server.Database;
import SIIL.Servicios.Grua.View.Resumov.TitemAdd;
import SIIL.Server.TargetMov;
import SIIL.Server.Titem;
import SIIL.Servicios.MovCreate;
import SIIL.trace.Trace;
import SIIL.trace.Value;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Azael
 */
public class Move extends javax.swing.JInternalFrame 
{
    //SIIL.Servicios.Grua.Elements.Movement  movs;
    /**
     * Creates new form Move
     * @param dp
     * @param credential
     */
    public Move(javax.swing.JDesktopPane dp,session.Credential credential) 
    {
        initComponents(); 
        //movs = new SIIL.Servicios.Grua.Elements.Movement();
        desktopPane = dp;
        grOwner.add(opSIIL);
        grOwner.add(opClient);
        BD = credential.getBD();
        this.credential = credential;
        mov = new SIIL.Server.Movimiento();
        titems = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnTree = new javax.swing.JPopupMenu();
        mnTreeForklift = new javax.swing.JMenu();
        mnTreeForkliftAdd = new javax.swing.JMenuItem();
        mnTreeForkliftDrop = new javax.swing.JMenuItem();
        grOwner = new javax.swing.ButtonGroup();
        btClient = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txfirma = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaNota = new javax.swing.JTextArea();
        btGuardar = new javax.swing.JButton();
        lbClient = new javax.swing.JLabel();
        Propietario = new javax.swing.JLabel();
        opClient = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        opSIIL = new javax.swing.JRadioButton();
        txFolio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbSuc = new javax.swing.JComboBox();
        txfhmov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbtmov = new javax.swing.JComboBox();
        cbusomov = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txSA = new javax.swing.JTextField();
        opNote = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txClient = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTitems = new javax.swing.JTable();
        btBattery = new javax.swing.JButton();
        btCharger = new javax.swing.JButton();
        btForklift = new javax.swing.JButton();

        mnTreeForklift.setText("jMenu1");

        mnTreeForkliftAdd.setText("jMenuItem1");
        mnTreeForklift.add(mnTreeForkliftAdd);

        mnTreeForkliftDrop.setText("jMenuItem1");
        mnTreeForklift.add(mnTreeForkliftDrop);

        mnTree.add(mnTreeForklift);

        setClosable(true);
        setResizable(true);

        btClient.setText("...");
        btClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Firma");

        jLabel8.setText("Nota");

        txaNota.setColumns(20);
        txaNota.setRows(5);
        jScrollPane1.setViewportView(txaNota);

        btGuardar.setText("Guardar");
        btGuardar.setToolTipText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        lbClient.setText("##");

        Propietario.setText("Propietario");

        opClient.setText("Cliente");

        jLabel1.setText("No. de Movimiento");

        opSIIL.setText("SIIL");

        jLabel12.setText("Sucursal");

        jLabel2.setText("Fecha (dd/mm/yyyy)");

        cbSuc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccion...", "Tijuana", "Ensenada", "Mexicali" }));
        cbSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucActionPerformed(evt);
            }
        });

        txfhmov.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfhmovFocusLost(evt);
            }
        });

        jLabel3.setText("Tipo");

        cbtmov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..", "Entrada", "Salida", "Movimiento", "Retorno", "Cancelar" }));
        cbtmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtmovActionPerformed(evt);
            }
        });

        cbusomov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..", "Disponible", "Renta Corto Plazo", "Préstamo", "Renta Opcion de Compra", "Reparación", "Venta", "Movimiento", "T. de Pintura", "Cubriendo", "Otras...", " " }));
        cbusomov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbusomovActionPerformed(evt);
            }
        });

        jLabel4.setText("Uso");

        jLabel5.setText("S.A.");

        txSA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txSAFocusLost(evt);
            }
        });

        opNote.setText("Agregar a hoja de Renta");

        jLabel6.setText("Cliente");

        txClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txClientKeyReleased(evt);
            }
        });

        tbTitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Eco.", "Serie", "Modelo", "Marca", "Horometro", "Equipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbTitems);

        btBattery.setText("Bateria");
        btBattery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatteryActionPerformed(evt);
            }
        });

        btCharger.setText("Cargador");
        btCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChargerActionPerformed(evt);
            }
        });

        btForklift.setText("Montacargas");
        btForklift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btForkliftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Propietario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(opClient)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(opSIIL))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbusomov, 0, 148, Short.MAX_VALUE)
                                            .addComponent(cbtmov, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbSuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txfhmov, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(txFolio))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txSA, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opNote)
                                    .addComponent(jLabel8))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBattery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCharger)
                                .addGap(18, 18, 18)
                                .addComponent(btForklift)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txClient, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btClient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbClient)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btGuardar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Propietario)
                            .addComponent(opClient)
                            .addComponent(opSIIL))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txfhmov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbtmov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbusomov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opNote)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txClient, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbClient))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btBattery)
                        .addComponent(btCharger)
                        .addComponent(btForklift))
                    .addComponent(cbSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientActionPerformed
        comp = new SIIL.Server.Company();
        JFrame frm = new JFrame();
        JDialog dlg = new JDialog(frm,"Seleccionar cliente",true);
        SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();        
        Database dbserver = null;
        try 
        {
            serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
            dbserver = new Database(serverConfig);
        }
        catch (ClassNotFoundException | SQLException | IOException | ParserConfigurationException | SAXException ex) 
        {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
            //fail(ex.getMessage());
        }
        
        if(dbserver.getConnection() == null)
        {
            JOptionPane.showMessageDialog(this,
                "Conexion a Servidor Invalida",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        SIIL.Clientes.ReadSelect read = new SIIL.Clientes.ReadSelect(comp,BD);
        dlg.setContentPane(read);
        dlg.setSize(460, 260);
        dlg.setVisible(true);
        txClient.setText(comp.getNumber());
        lbClient.setText(comp.getName());
    }//GEN-LAST:event_btClientActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();
        Database dbserver = null;
        try 
        {
            serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
            dbserver = new Database(serverConfig);
        } 
        catch (ClassNotFoundException | SQLException | IOException | ParserConfigurationException | SAXException ex) 
        {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
        }
        
        Trace trace = new Trace(credential.getBD(),credential.getUser(), "Movimiento de Grua : " + txfhmov.getText() + " - " + txFolio.getText());   
        try 
        {
            int reg = trace.insert(dbserver);
            if(reg != 1)
            {
                JOptionPane.showMessageDialog(this,
                "Falló la creación de la bitacora, registros afectados " + reg,
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
                );
            }
            Value val = new Value();
            
            val = new Value();
            val.setTraceID(trace.getTrace());
            val.setTable("Grua");
            val.setField("operator");
            val.setAfter(credential.getUser().toString());
            val.setBrief("Quien hace");
            val.setLlave("-");
            val.insert(dbserver);
            val = new Value();
            val.setTraceID(trace.getTrace());
            val.setTable("Grua");
            val.setField("folio");
            val.setAfter(txFolio.getText());
            val.setBrief("Folio");
            val.setLlave("-");
            val.insert(dbserver);

            val = new Value();
            val.setTraceID(trace.getTrace());
            val.setTable("Grua");
            val.setField("fhmov");
            val.setAfter(txfhmov.getText());
            val.setBrief("Fecha");
            val.setLlave("-");
            val.insert(dbserver);
            val = new Value();

            val.setTraceID(trace.getTrace());
            val.setTable("Grua");
            val.setField("tipo");
            val.setAfter(cbtmov.getSelectedItem().toString());
            val.setBrief("Tipo");
            val.setLlave("-");
            val.insert(dbserver);

            val = new Value();
            val.setTraceID(trace.getTrace());
            val.setTable("Grua");
            val.setField("uso");
            val.setAfter(cbusomov.getSelectedItem().toString());
            val.setBrief("Uso");
            val.setLlave("-");
            val.insert(dbserver);
            
            for(Titem t : titems)
            {
                val = new Value();
                val.setTraceID(trace.getTrace());
                val.setTable("Grua");
                val.setField("Hequi");
                val.setAfter(t.getNumber());
                val.setBrief("Equipo movido");
                val.setLlave("-");
                val.insert(dbserver);
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Move.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                ex,
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if(convertTMov(cbtmov).equals("ent") && convertUso(cbusomov).equals("rep") && opSIIL.isSelected())
        {
            forReparacion(dbserver);
        }
        else if(convertTMov(cbtmov).equals("canc"))
        {
            forCancel(dbserver);
        }
        else if(convertTMov(cbtmov).equals("ret"))
        {
            forRecuperacion(dbserver);
        }
        else if(opClient.isSelected())
        {
            forClient(dbserver);
        }
        else if(opSIIL.isSelected())
        {
            forSIIL(dbserver);
        }                
    }//GEN-LAST:event_btGuardarActionPerformed

    private void cbSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSucActionPerformed

    private void txfhmovFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfhmovFocusLost
        validFhMov();
    }//GEN-LAST:event_txfhmovFocusLost

    private void cbtmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtmovActionPerformed
        if(cbtmov.getSelectedIndex() == 4)
        {
            cbusomov.setEnabled(false);
            txSA.setEnabled(false);
            txClient.setEnabled(false);
            btClient.setEnabled(false);
        }
        else if(cbtmov.getSelectedIndex() == 5)
        {
            cbusomov.setEnabled(false);
            txSA.setEnabled(false);
            txClient.setEnabled(false);
            btClient.setEnabled(false);
            txfirma.setEnabled(false);
            cbSuc.setEnabled(false);
            txClient.setEnabled(false);
            opClient.setEnabled(false);
            opSIIL.setEnabled(false);
        }
        else
        {
            cbusomov.setEnabled(true);
            txSA.setEnabled(true);
            txClient.setEnabled(true);
            btClient.setEnabled(true);
            txfirma.setEnabled(true);
            cbSuc.setEnabled(true);
            txClient.setEnabled(true);
            opClient.setEnabled(true);
            opSIIL.setEnabled(true);
        }
    }//GEN-LAST:event_cbtmovActionPerformed

    private void cbusomovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbusomovActionPerformed
        if( cbtmov.getSelectedIndex() == 3 && cbusomov.getSelectedIndex() == 7 && opSIIL.isSelected() )
        {
            txClient.setEnabled(false);
            lbClient.setEnabled(false);
            btClient.setEnabled(false);
        }
        else
        {
            txClient.setEnabled(true);
            lbClient.setEnabled(true);
            btClient.setEnabled(true);
        }
    }//GEN-LAST:event_cbusomovActionPerformed

    private void txSAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSAFocusLost
        
    }//GEN-LAST:event_txSAFocusLost

    private void txClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txClientKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            comp = new SIIL.Server.Company();
            comp.setBD(BD);
            comp.setNumber(txClient.getText());
            SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();
            Database dbserver = null;
            try 
            {
                serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
                dbserver = new Database(serverConfig);
            } 
            catch (ClassNotFoundException | SQLException | IOException | ParserConfigurationException | SAXException ex) 
            {
                Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
            }
            if(dbserver.getConnection() == null)
            {
                JOptionPane.showMessageDialog(this,
                    "La conexión al Servidor es invalida",
                    "Error Interno",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            if(comp.complete(dbserver))
            {
                lbClient.setText(comp.getName());
            }
            else
            {
                if(comp == null)
                {
                    JOptionPane.showMessageDialog(this, "Numero de cliente desconocido",
                        "Error externo", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    comp=null;
                    lbClient.setText("###");
                }
            }
            dbserver.close();
        }
    }//GEN-LAST:event_txClientKeyReleased

    private void btBatteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatteryActionPerformed
        String strOwner;
        if(opClient.isSelected())
        {
            strOwner = "client";
        }
        else if(opSIIL.isSelected())
        {
            strOwner = "SIIL";
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Indique el propietario del Equipo", "Error Externo"
                , JOptionPane.ERROR_MESSAGE);
            return;
        }
        TitemAdd capFork = new TitemAdd(tbTitems,"battery",strOwner,titems,BD);
        desktopPane.add(capFork);
        int x = desktopPane.getSize().width/2 - capFork.getSize().width/2;
        int y = 10;
        capFork.setLocation(x, y);
        capFork.setVisible(true);
    }//GEN-LAST:event_btBatteryActionPerformed

    private void btChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChargerActionPerformed
        String strOwner;
        if(opClient.isSelected())
        {
            strOwner = "client";
        }
        else if(opSIIL.isSelected())
        {
            strOwner = "SIIL";
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Indique el propietario del Equipo", "Error Externo"
                , JOptionPane.ERROR_MESSAGE);
            return;
        }
        TitemAdd capFork = new TitemAdd(tbTitems,"charger",strOwner,titems,BD);
        desktopPane.add(capFork);
        int x = desktopPane.getSize().width/2 - capFork.getSize().width/2;
        int y = 10;
        capFork.setLocation(x, y);
        capFork.setVisible(true);
    }//GEN-LAST:event_btChargerActionPerformed

    private void btForkliftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btForkliftActionPerformed
        String strOwner;
        if(opClient.isSelected())
        {
            strOwner = "client";
        }
        else if(opSIIL.isSelected())
        {
            strOwner = "SIIL";
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Indique el propietario del Equipo", "Error Externo"
                , JOptionPane.ERROR_MESSAGE);
            return;
        }
        TitemAdd capFork = new TitemAdd(tbTitems,"forklift",strOwner,titems,BD);
        desktopPane.add(capFork);
        int x = desktopPane.getSize().width/2 - capFork.getSize().width/2;
        int y = 10;
        capFork.setLocation(x, y);
        capFork.setVisible(true);
    }//GEN-LAST:event_btForkliftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Propietario;
    private javax.swing.JButton btBattery;
    private javax.swing.JButton btCharger;
    private javax.swing.JButton btClient;
    private javax.swing.JButton btForklift;
    private javax.swing.JButton btGuardar;
    private javax.swing.JComboBox cbSuc;
    private javax.swing.JComboBox cbtmov;
    private javax.swing.JComboBox cbusomov;
    private javax.swing.ButtonGroup grOwner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbClient;
    private javax.swing.JPopupMenu mnTree;
    private javax.swing.JMenu mnTreeForklift;
    private javax.swing.JMenuItem mnTreeForkliftAdd;
    private javax.swing.JMenuItem mnTreeForkliftDrop;
    private javax.swing.JRadioButton opClient;
    private javax.swing.JCheckBox opNote;
    private javax.swing.JRadioButton opSIIL;
    private javax.swing.JTable tbTitems;
    private javax.swing.JTextField txClient;
    private javax.swing.JTextField txFolio;
    private javax.swing.JTextField txSA;
    private javax.swing.JTextArea txaNota;
    private javax.swing.JTextField txfhmov;
    private javax.swing.JTextField txfirma;
    // End of variables declaration//GEN-END:variables

    SIIL.Server.Company comp;
    String BD;
    SIIL.Server.Movimiento mov;
    SIIL.Server.Forklift forklift;
    ArrayList<SIIL.Server.Titem> titems;
    SIIL.Server.Battery battery;
    SIIL.Server.Charger charger;
    javax.swing.JDesktopPane desktopPane;
    session.Credential credential;
    
    
    private boolean validFolio() 
    {
        if(txFolio.getText().matches("^00[1-9]|0[1-9][0-9]|[12][0-9][0-9]|300$"))// 
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "En el folio es un valor numerico entre 001 y 300.", "Error Externo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    
    }

    private boolean validFhMov() 
    {
        if(txFolio.getText().matches("^00[1-9]|0[1-9][0-9]|[12][0-9][0-9]|300$"))// 
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "En el folio es un valor numerico entre 001 y 300.", "Error Externo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    private TargetMov deduceTarget(ArrayList<SIIL.Server.Titem> ts) 
    {
        int iFork = 0;
        int iCharg = 0;
        int iBatt = 0;
        
        //ArrayList<SIIL.Server.Titem> ts = mov.getTitems();
        for (Titem t : ts) 
        {
            String strclass = t.toString().split("@")[0];
            switch (strclass) 
            {
                case "SIIL.Server.Forklift":
                    iFork++;
                    forklift = (SIIL.Server.Forklift) t;
                    break;
                case "SIIL.Server.Charger":
                    iCharg++;
                    charger = (SIIL.Server.Charger) t;
                    break;
                case "SIIL.Server.Battery":
                    iBatt++;
                    battery = (SIIL.Server.Battery) t;
                    break;
            }
        }
        
        if(iFork == 1 && iCharg == 1 && iBatt == 1)
        {
            forklift.setBattery(battery);
            forklift.setCharger(charger);
            return TargetMov.Forklift;
        }
        else if(iFork == 1 && iCharg == 1)
        {
            forklift.setCharger(charger);
            return TargetMov.Forklift;
        }
        else if(iFork == 1 && iBatt == 1)
        {
            forklift.setBattery(battery);
            return TargetMov.Forklift;
        }
        else if(iFork == 1)
        {
            return TargetMov.Forklift;
        }
        else if(iFork == 0 && iBatt == 1)
        {
            return TargetMov.Battery;
        }
        else if(iFork == 0 && iCharg  == 1)
        {
            return TargetMov.Battery;
        }
        else if(iFork == 0 && iBatt > 1)
        {
            return TargetMov.Batteries;
        }
        
        return TargetMov.Ambiguous;
    }
    private void forRecuperacion(Database conn) 
    {        
        forReturn(SIIL.Server.Movimiento.Command.Recuperacion,conn);        
    }
    
    private void forReparacion(Database conn) 
    {        
        forReturn(SIIL.Server.Movimiento.Command.Reparacion,conn);        
    }
    
    private void forReturn(SIIL.Server.Movimiento.Command cmd,Database conn)
    {
        mov.setBD(BD);
        if(opClient.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Está operacion no puede ser aplicada con clientes"
                    , "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(opSIIL.isSelected())
        {
            mov.setOwner("SIIL");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique el propietario del equipo.", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(validFolio())
        {
            mov.setFolio(txFolio.getText());
        }
        
        if(txfhmov.getText().length() > 0)
        {
            try 
            {
                mov.setFhMov(txfhmov.getText());
            } 
            catch (ParseException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique la fecha del movimiento", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txfirma.getText().length() > 0 )
        {
            mov.setFirma(txfirma.getText());
        }
        if(converSuc() == null)
        {
            JOptionPane.showMessageDialog(this, "Indique la sucursal", "Error Externo", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            mov.setSucursal(converSuc()); 
        }       
        TargetMov targetmov = deduceTarget(titems);
                
        if(txaNota.getText().length()>0)
        {
            mov.setNote(txaNota.getText());
        }
        if(txSA.getText().length()>0)
        {
            mov.setSA(txSA.getText());
        }
        if(comp != null)
        {
            mov.setCompany(comp);
        }
        mov.setTmov(convertTMov(cbtmov));
        mov.setUso(convertUso(cbusomov));
        
        
        //SIIL.Server.Resumov rmov = new SIIL.Server.Resumov();
        int flRet;
        
        if(targetmov == TargetMov.Forklift)
        {
            flRet = mov.Return(conn,forklift,titems,cmd,opNote.isSelected());
        }
        else if(targetmov == TargetMov.Battery)
        {
            flRet=0;
            try {
                flRet = mov.insert(conn, titems);
            } catch (Exception ex) {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "La operacion de retorno es para un montacargas o bateria, mas de uno causa ambigüedad del objeto a retornar"
                    , "Error Externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //minio es el registro de movimiento, registro del objetivo y el update para resumov.
        //maximo es el registro de movimiento y un registro por cada Titem
        //tambien se actualizan las sucursales de cada titem
        if(flRet > 1 &&  flRet < titems.size() * 2 + 3  && titems.size() > 0)
        {
            try 
            {
                conn.commit();
                JOptionPane.showMessageDialog(this, "Operación completada exitosamente.");
                dispose();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try 
            {
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Operación Fallida","Error Interno", JOptionPane.ERROR_MESSAGE);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private boolean validSA() 
    {
        if(txSA.getText().matches("^[0-9]+$"))
        {
            return true;
        }        
        else if(txSA.getText().length()>0 && !txSA.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "EL formato del SA es incorrecto",
                        "Error Externo", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        else
        {
            return false;
        }
    }

    public String convertUso(JComboBox cbusomov) 
    {
        switch(cbusomov.getSelectedIndex())
        {
            case 0:
                break;
            case 1:
                return "disp";
            case 2:
                return "rtacp";
            case 3:
                return "pres";
            case 4:   
                return "rtaoc"; 
            case 5:    
                return "rep";  
            case 6:    
                return "vta"; 
            case 7:    
                return "mov";  
            case 8:
                return "tpint";
            case 9:
                return "corr";
            case 10:
                return "otras";
        }
        return "";
    }

    private boolean validTMov() 
    {
        if(cbtmov.getSelectedIndex()>0) 
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique el tipo de movimiento",
                    "Error Externo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validUso() 
    {
        if(cbusomov.getSelectedIndex() > 0 )
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique el Uso del montacargas",
                    "Error Externo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validCompany() 
    {
        if(comp == null)
        {
            JOptionPane.showMessageDialog(this, "Indique el cliente",
                    "Error Externo", JOptionPane.ERROR_MESSAGE);
            return false;            
        }
        return true;
    }

    private boolean validFirma() 
    {
        if(txfirma.getText().length()>0)
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Especifique quien firma",
                    "Error Externo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validNote() 
    {
        return true;
    }

    private String converSuc() 
    {
        switch((String)cbSuc.getSelectedItem())
        {
            case "Tijuana":
                return "bc.tj";
            case "Mexicali":
                return "bc.mx";
            case "Ensenada":
                return "bc.ens";
        }
        return null;
    }

    private void forClient(Database conn)
    {
        mov.setBD(BD);
        if(opClient.isSelected())
        {
            mov.setOwner("client");
        }
        else if(opSIIL.isSelected())
        {
            mov.setOwner("SIIL");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique el propietario del equipo.", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(validFolio())
        {
            mov.setFolio(txFolio.getText());
        }
        
        if(txfhmov.getText().length() > 0)
        {
            try 
            {
                mov.setFhMov(txfhmov.getText());
            } 
            catch (ParseException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique la fecha del movimiento", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        mov.setTmov(convertTMov(cbtmov));
        mov.setUso(convertUso(cbusomov));
        
        if(txSA.getText().length() > 0)
        {
            mov.setSA(txSA.getText());
        }
                
        if(comp != null )
        {
            mov.setCompany(comp);
        }
        else if(cbtmov.getSelectedIndex() != 4)
        {
            JOptionPane.showMessageDialog(this, "Indique el cliente", "Error externo", JOptionPane.ERROR_MESSAGE);
        }
        
        if(txfirma.getText().length() > 0 )
        {
            mov.setFirma(txfirma.getText());
        }
        
        if(converSuc() == null)
        {
            JOptionPane.showConfirmDialog(this, "Indique la sucursal", "Error Externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            mov.setSucursal(converSuc()); 
        }
        mov.setNote(txaNota.getText());
        
        if(comp != null )
        {
            mov.setCompany(comp);
        }
        else if(cbtmov.getSelectedIndex() != 4)
        {
            JOptionPane.showMessageDialog(this, "Seleccione el cliente", "Error externo"
                    , JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int flMov = 0;
        try 
        {
            flMov = mov.insert(conn,titems);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if(flMov == 1 + titems.size()  && titems.size() > 0)
        {
            try 
            {
                conn.commit();   
                JOptionPane.showMessageDialog(this, "Todos los datos se guardaron correctamente.");
                dispose();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try 
            {
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Un error inesperado ocurrio, ningún dato será guardado.", "Error interno", JOptionPane.ERROR_MESSAGE);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        conn.close();
    }

    private String convertTMov(JComboBox cbtmov) 
    {
        switch(cbtmov.getSelectedIndex())
        {
            case 0:
                return null;
            case 1:
                return "ent";
            case 2:
                return "sal";
            case 3:
                return "mov";
            case 4:
                return "ret";
            case 5:
                return "canc";
        }
        return null;
    }

    private void forSIIL(Database conn) 
    {
        mov.setBD(BD);
        if(opClient.isSelected())
        {
            mov.setOwner("client");
        }
        else if(opSIIL.isSelected())
        {
            mov.setOwner("SIIL");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique el propietario del equipo.", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(validFolio())
        {
            mov.setFolio(txFolio.getText());
        }
        
        if(txfhmov.getText().length() > 0)
        {
            try 
            {
                mov.setFhMov(txfhmov.getText());
            } 
            catch (ParseException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique la fecha del movimiento", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        mov.setTmov(convertTMov(cbtmov));
        mov.setUso(convertUso(cbusomov));
        
        if(txSA.getText().length() > 0)
        {
            mov.setSA(txSA.getText());
        }
        
        if( cbtmov.getSelectedIndex() == 3 && cbusomov.getSelectedIndex() == 7 )
        {
            ;//se optendra de la base de datos
        }
        else if(comp != null )
        {
            mov.setCompany(comp);
        }
        else if(cbtmov.getSelectedIndex() != 4)
        {
            JOptionPane.showMessageDialog(this, "Seleccione el cliente", "Error externo"
                    , JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txfirma.getText().length() > 0 )
        {
            mov.setFirma(txfirma.getText());
        }
        if(converSuc() == null)
        {
            JOptionPane.showMessageDialog(this, "Indique la sucursal", "Error Externo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            mov.setSucursal(converSuc()); 
        }
        mov.setNote(txaNota.getText());
        
        
        SIIL.Server.Resumov rmov = new SIIL.Server.Resumov();
        TargetMov targetmov = deduceTarget(titems);
        boolean flB = true;
        boolean flC = true;
        int flRMov = 0;
                
        if(targetmov == TargetMov.Forklift)
        {
            forklift.downSucursal(conn);//antes de asignar la sucursal
            /*if(!forklift.getSucursal().equals("bc.tj"))//No esta en la matriz?
            {
                //es de diferente sucursal?
                if(!forklift.getSucursal().equals(SIIL.servApp.cred.getSuc()))
                {
                    JOptionPane.showMessageDialog(this, "El montacargas no perteneces a la sucursal actual, solicite a el movimeitno a matriz", "Error Externo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }*/
            if(forklift.getBattery() != null)
            {
                flB = forklift.linkBattery(conn);
                if(!flB)
                {
                    JOptionPane.showMessageDialog(this, "Parece que la bateria ya está enlazada o no se encontro el numero Ecónomico solicitado, "  + forklift.getBattery().getNumber(), "Error Externo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if(forklift.getCharger() != null)
            {
                flC = forklift.linkCharger(conn);
                if(!flC)
                {
                    JOptionPane.showMessageDialog(this, "Parece que el cargador ya está enlazada o no se encontro el numero Ecónomico solicitado, "  + forklift.getCharger().getNumber(), "Error Externo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            rmov.setForklift(forklift);
            
            //Para movimiento-movimiento no se hactualiza la resumov
            if(mov.getUso().equals("mov") && mov.getTmov().equals("mov"))
            {
                rmov.downloadCompany(conn);
                mov.setCompany(rmov.getCompany());
            }
            else if(comp != null)
            {
                rmov.setCompany(comp);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Indique el cliente", "Error Externo", JOptionPane.ERROR_MESSAGE);
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
                }
                return;
            }
            rmov.setUso(convertUso(cbusomov));
            if(opNote.isSelected())
            {
                rmov.setNote(txaNota.getText());
            }
            else
            {
                rmov.setNote("");
            }
            rmov.setSucursal(converSuc());
            try 
            {
                rmov.setFhMov(txfhmov.getText());
            } 
            catch (ParseException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            flRMov = rmov.update(conn);
        }
        else if(targetmov == TargetMov.Battery || targetmov == TargetMov.Batteries)
        {
            flRMov = -1;
        }
        
        int flMov = 0;
        try 
        {
            flMov = mov.insert(conn,titems);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if((flMov <= 1 + titems.size()*2) && ( flB && flC && ( flRMov == 1 || flRMov == -1)) && titems.size() > 0)
        {
            try 
            {
                conn.commit();   
                JOptionPane.showMessageDialog(this, "Todos los datos se guardaron correctamente.");
                dispose();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try 
            {
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Un error inesperado ocurrio, ningún dato será guardado.", "Error interno", JOptionPane.ERROR_MESSAGE);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        conn.close();
    }

    private void cleanTitems() 
    {
        DefaultTableModel dm = ((DefaultTableModel)tbTitems.getModel());
        int rows = dm.getRowCount();
        for(int i = 0; i < rows; ++i)
        {
            dm.removeRow(0);
        }
    }

    private void forCancel(Database conn) 
    {
        if(validFolio())
        {
            mov.setFolio(txFolio.getText());
        }
        
        if(txfhmov.getText().length() > 0)
        {
            try 
            {
                mov.setFhMov(txfhmov.getText());
            } 
            catch (ParseException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Indique la fecha del movimiento", "Error externo", JOptionPane.ERROR_MESSAGE);
            return;
        }        
        mov.setNote(txaNota.getText());
        mov.setBD(BD);
        mov.setTmov(convertTMov(cbtmov));
        
        int flMov = 0;
        try 
        {
            flMov = mov.insert(conn,titems);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        if(flMov == 1)
        {
            try 
            {
                conn.commit();   
                JOptionPane.showMessageDialog(this, "Todos los datos se guardaron correctamente.");                
                dispose();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try 
            {
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Un error inesperado ocurrio, ningún dato será guardado.", "Error interno", JOptionPane.ERROR_MESSAGE);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(MovCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        conn.close();
    }
}
