
package sales.quotation;

import SIIL.Server.Database;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Azael Reyes
 */
public class Read2 extends javax.swing.JPanel 
{
    private Database dbserver;

    private int getSelectRow() 
    {
        if(tbList.getSelectedRow() < 0 ) 
        {
            return tbList.getSelectedRow();
        }
        else
        {
            ReadTableModel model = (ReadTableModel) tbList.getModel();            
            return tbList.convertRowIndexToModel(tbList.getSelectedRow());
        }
    }
    
    private void openDatabase(boolean  reclicleConextion)
    {
        try 
        {
            SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();
            serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
        
            if(reclicleConextion)
            {
                if(dbserver != null)
                {
                    if(dbserver.getConnection().isValid(50))
                    {
                        return;
                    }
                    else
                    {
                        ;
                    }
                }
                else
                {
                    
                }
            }
            else
            {
                if(dbserver != null)
                {
                    if(!dbserver.getConnection().isClosed()) dbserver.close();
                    dbserver = null;                    
                }
            }
            dbserver = null;
            dbserver = new Database(serverConfig);
        }
        catch (IOException | ClassNotFoundException | SQLException | ParserConfigurationException | SAXException ex) 
        {
            JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void closeDatabase() 
    {
        if(dbserver != null)
        {
            dbserver.close();
            dbserver = null;
        }
    }
    
    /**
     * Creates new form Read2
     */
    public Read2() 
    {
        initComponents();
        
        ReadTableModel model = (ReadTableModel) tbList.getModel();
        try 
        {
            openDatabase(true);
            model.download(dbserver);
        }
        catch (SQLException ex) 
        {
            //Logger.getLogger(Read2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        mnMain = new javax.swing.JPopupMenu();
        mnCreate = new javax.swing.JMenuItem();
        mnAdd = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbList = new org.jdesktop.swingx.JXTable();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);

        mnCreate.setText("Crear");
        mnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCreateActionPerformed(evt);
            }
        });
        mnMain.add(mnCreate);

        mnAdd.setText("Detalle");
        mnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddActionPerformed(evt);
            }
        });
        mnMain.add(mnAdd);

        tbList.setModel(new ReadTableModel());
        tbList.setComponentPopupMenu(mnMain);
        jScrollPane2.setViewportView(tbList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCreateActionPerformed
        Create screen = new Create();
        core.Dialog dialog = new core.Dialog(screen);
        dialog.setContent(screen);
    }//GEN-LAST:event_mnCreateActionPerformed

    private void mnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddActionPerformed
        if(getSelectRow() < 0)
        {
            JOptionPane.showMessageDialog(
                this,
                "Seleccion un renglon",
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        JInternalFrame inter = new JInternalFrame("Enviar correo de Factura",false,true);
        ReadTableModel model = (ReadTableModel) tbList.getModel();
        Detalle screen = new Detalle(model.getValueAt(getSelectRow()));
        inter.setContentPane(screen);
        inter.setSize(screen.getPreferredSize());
        inter.setMaximizable(true);
        SIIL.servApp.getInstance().getDesktopPane().add(inter);
        int x = SIIL.servApp.getInstance().getDesktopPane().getSize().width/2 - screen.getSize().width/2;
        int y = 10;
        inter.setLocation(x, y);
        inter.setVisible(true);        
    }//GEN-LAST:event_mnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JMenuItem mnAdd;
    private javax.swing.JMenuItem mnCreate;
    private javax.swing.JPopupMenu mnMain;
    private org.jdesktop.swingx.JXTable tbList;
    // End of variables declaration//GEN-END:variables
}
