
package SIIL.Instances;

import SIIL.Server.Database;
import SIIL.sockets.messages.SynchronizeApplication;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Azael Reyes
 */
public class Read extends javax.swing.JPanel 
{
    /**
     * Creates new form Read
     */
    public Read() 
    {
        initComponents();
        ReadTableModel model = (ReadTableModel) tbList.getModel();
        SIIL.core.config.Server serverConfig = new SIIL.core.config.Server();
        Database dbserver = null;
        try 
        {
            serverConfig.loadFile(new java.io.File(".").getCanonicalPath());
        } 
        catch (IOException | ParserConfigurationException | SAXException ex) 
        {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
        }
            
        try 
        {
            model.load(dbserver);
        }
        catch (SQLException ex) 
        {
            //Logger.getLogger(Read.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error Interno",
                JOptionPane.ERROR_MESSAGE
            );
        }
        dbserver.close();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnMain = new javax.swing.JPopupMenu();
        mnSynch = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new org.jdesktop.swingx.JXTable();

        mnSynch.setText("Sincronizar");
        mnSynch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSynchActionPerformed(evt);
            }
        });
        mnMain.add(mnSynch);

        tbList.setModel(new ReadTableModel());
        tbList.setComponentPopupMenu(mnMain);
        jScrollPane1.setViewportView(tbList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mnSynchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSynchActionPerformed
        if(SIIL.servApp.socket != null)
        {
            SIIL.servApp.socket.send(new SynchronizeApplication(null));
        }
    }//GEN-LAST:event_mnSynchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu mnMain;
    private javax.swing.JMenuItem mnSynch;
    private org.jdesktop.swingx.JXTable tbList;
    // End of variables declaration//GEN-END:variables
}
