
package SIIL.purchase.cr;

import javax.swing.JOptionPane;

/**
 *
 * @author Azael
 */
public class CUDocs extends javax.swing.JInternalFrame 
{

    CUDocs(CU cu, Factura fac, ModeOperation modeOperation) 
    {
        initComponents();
        this.cu = cu;
        this.factura = fac;
        this.modeOperation = modeOperation;
        
        CUDocsTableModel tm = (CUDocsTableModel) tbList.getModel();
        tm.setList(fac.getDocuments());
        if(this.modeOperation == ModeOperation.EDIT)
        {
            txFolio.setText(fac.getFolio());
            txMonto.setText(String.valueOf(fac.getMonto()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txMonto = new javax.swing.JTextField();
        btAddDoc = new javax.swing.JButton();

        setClosable(true);
        setTitle("Crear Factura");

        jLabel1.setText("Factura");

        jLabel2.setText("Documentos");

        tbList.setModel(new CUDocsTableModel());
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);

        btAdd.setText("Agregar Factura");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel3.setText("Monto");

        btAddDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btAddDoc.setMnemonic('+');
        btAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAddDoc))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txMonto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txFolio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btAddDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        
        if(txFolio.getText().matches("^([0-9]|[a-z]|[A-Z])+$"))
        {
            factura.setFolio(txFolio.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El folio solo esta formado por letras y números","Error externo",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //
        if(txMonto.getText().matches("^[-|+]?[0-9]+.[0-9]{2,2}$"))
        {
            factura.setMonto(Float.parseFloat(txMonto.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El monto es un número real con dos decimales","Error externo",JOptionPane.ERROR_MESSAGE);
            return;
        }
              
        cu.loadTable();
        dispose();
    }//GEN-LAST:event_btAddActionPerformed

    private void btAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDocActionPerformed
        SIIL.purchase.cr.CUDocsAdd docs = new SIIL.purchase.cr.CUDocsAdd(this,factura);
        getDesktopPane().add(docs);
        int x = getDesktopPane().getSize().width/2 - docs.getSize().width/2;
        int y = 10;
        docs.setLocation(x, y);
        docs.setVisible(true);
    }//GEN-LAST:event_btAddDocActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
        if (evt.getClickCount() == 2) 
        {
            if(tbList.getSelectedRow() > -1)
            {
                ;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Primero seleccione un registro.",
                        "Error Externo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Document doc = ((CUDocsTableModel)tbList.getModel()).getDocument(tbList.getSelectedRow());
            SIIL.purchase.cr.CUDocsAdd docs = new SIIL.purchase.cr.CUDocsAdd(this,doc);
            getDesktopPane().add(docs);
            int x = getDesktopPane().getSize().width/2 - docs.getSize().width/2;
            int y = 10;
            docs.setLocation(x, y);
            docs.setVisible(true);
        }
    }//GEN-LAST:event_tbListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbList;
    private javax.swing.JTextField txFolio;
    private javax.swing.JTextField txMonto;
    // End of variables declaration//GEN-END:variables
    CU cu;    
    private Factura factura;
    private ModeOperation modeOperation;
    

    /**
     * @return the tbList
     */
    public javax.swing.JTable getTable() {
        return tbList;
    }

    void reloadTable() 
    {
        cleanTable();
        loadTable();
    }

    void cleanTable() 
    {
        CUDocsTableModel dm = ((CUDocsTableModel)tbList.getModel());
        dm.clear();        
    }

    void loadTable() 
    {
        CUDocsTableModel dm = ((CUDocsTableModel)tbList.getModel());
        dm.fireTableDataChanged();
    }

    /**
     * @return the fac
     */
    public Factura getFactura() {
        return factura;
    }
}
